<?php
/**
 * 写作参数定义配置
 * 
 * 集中管理所有写作参数的元数据定义，包括标签、类型、默认值、范围等。
 * 被 writing_settings.php 和 API 接口共享使用。
 */

return [
    // ========== 基础生成参数 ==========
    'ws_chapter_words' => [
        'label'   => '每章目标字数',
        'type'    => 'number',
        'default' => 2000,
        'min'     => 500,
        'max'     => 5000,
        'step'    => 100,
        'unit'    => '字',
        'desc'    => '单章生成的目标字数。网文常见区间：1500-2500字。低于1500节奏过快、缺乏沉浸感；高于3000读者疲劳度上升。',
        'section' => '基础生成参数',
    ],
    'ws_chapter_word_tolerance' => [
        'label'   => '章节字数容差',
        'type'    => 'number',
        'default' => 150,
        'min'     => 50,
        'max'     => 500,
        'step'    => 50,
        'unit'    => '字',
        'desc'    => '允许正文偏离目标字数的范围（±N字）。值越小，字数控制越严格；值越大，AI写作更自然但篇幅更难预测。默认150字约为目标字数的3%-8%。',
        'section' => '基础生成参数',
    ],
    'ws_dynamic_tolerance_ratio' => [
        'label'   => '动态容差比例',
        'type'    => 'number',
        'default' => 10,
        'min'     => 5,
        'max'     => 20,
        'step'    => 1,
        'unit'    => '%',
        'desc'    => '根据目标字数动态计算容差比例。例如：2000字×10%=200字容差。替代固定容差值，使控制比例一致。',
        'section' => '基础生成参数',
    ],
    'ws_min_tolerance' => [
        'label'   => '最小容差字数',
        'type'    => 'number',
        'default' => 100,
        'min'     => 50,
        'max'     => 300,
        'step'    => 50,
        'unit'    => '字',
        'desc'    => '动态容差的下限值。防止目标字数过小时容差太小导致过于严格。',
        'section' => '基础生成参数',
    ],
    'ws_max_tolerance' => [
        'label'   => '最大容差字数',
        'type'    => 'number',
        'default' => 500,
        'min'     => 200,
        'max'     => 1000,
        'step'    => 100,
        'unit'    => '字',
        'desc'    => '动态容差的上限值。防止目标字数过大时容差太大导致控制失效。',
        'section' => '基础生成参数',
    ],
    'ws_outline_batch' => [
        'label'   => '大纲批量生成数',
        'type'    => 'number',
        'default' => 5,
        'min'     => 3,
        'max'     => 50,
        'step'    => 1,
        'unit'    => '章',
        'desc'    => '每次生成大纲时，一次性规划的章节数量。值越大，AI 对长程节奏把控越好，但生成耗时越长。默认5章，可根据网络稳定性调整。',
        'section' => '基础生成参数',
    ],
    'ws_outline_batch_1m' => [
        'label'   => '大纲批量生成数（1M模式）',
        'type'    => 'number',
        'default' => 30,
        'min'     => 10,
        'max'     => 100,
        'step'    => 5,
        'unit'    => '章',
        'desc'    => '1M上下文模型专用。每次可生成更多章节大纲，提升全书连贯性。仅当模型名称包含[1m]时生效。',
        'section' => '基础生成参数',
    ],
    'ws_context_mode' => [
        'label'   => '上下文模式',
        'type'    => 'select',
        'default' => 'auto',
        'options' => [
            'auto'      => '自动（根据模型选择）',
            'compressed'=> '压缩模式（节省token）',
            'full'      => '完整模式（需1M上下文模型）',
        ],
        'desc'    => '压缩模式：仅注入摘要和关键信息，节省token。完整模式：注入所有历史章节，确保100%一致性（需模型名称含[1m]）。自动模式会根据模型自动选择。',
        'section' => '基础生成参数',
    ],
    'ws_auto_write_interval' => [
        'label'   => '自动写作间隔',
        'type'    => 'number',
        'default' => 2,
        'min'     => 1,
        'max'     => 60,
        'step'    => 1,
        'unit'    => '秒',
        'desc'    => '连续自动写作时，每章之间的等待间隔。太短可能触发 API 限流；太长拖慢整体进度。',
        'section' => '基础生成参数',
    ],
    // ========== 爽点调度参数 ==========
    'ws_cool_point_density_target' => [
        'label'   => '爽点密度目标值',
        'type'    => 'range',
        'default' => 0.88,
        'min'     => 0.5,
        'max'     => 1.5,
        'step'    => 0.05,
        'unit'    => '个/章',
        'desc'    => '每章平均爽点数量目标。参考值：0.88（《万古神帝》实测密度）。低于0.6读者流失风险高；高于1.2容易审美疲劳。',
        'section' => '爽点调度参数',
    ],
    'ws_cool_point_hunger_threshold' => [
        'label'   => '爽点饥饿阈值',
        'type'    => 'range',
        'default' => 0.6,
        'min'     => 0.3,
        'max'     => 1.0,
        'step'    => 0.05,
        'unit'    => '',
        'desc'    => '某种爽点类型冷却期过多少比例后，可重新参选。值越低，同类型爽点出现越频繁；值越高，类型轮换越均匀。',
        'section' => '爽点调度参数',
    ],
    'ws_double_coolpoint_gap' => [
        'label'   => '双爽点最小间隔',
        'type'    => 'number',
        'default' => 3,
        'min'     => 1,
        'max'     => 10,
        'step'    => 1,
        'unit'    => '章',
        'desc'    => '连续出现"双爽点章"的最小间隔。防止高潮密度过高导致读者疲劳。推荐 2-4 章。',
        'section' => '爽点调度参数',
    ],
    // ========== 章节结构参数 ==========
    'ws_segment_ratio_setup' => [
        'label'   => '铺垫段占比',
        'type'    => 'range',
        'default' => 20,
        'min'     => 10,
        'max'     => 35,
        'step'    => 5,
        'unit'    => '%',
        'desc'    => '每章开头铺垫/引入部分的字数占比。用于交代场景、推进日常、制造悬念。',
        'section' => '章节结构参数',
    ],
    'ws_segment_ratio_rising' => [
        'label'   => '发展段占比',
        'type'    => 'range',
        'default' => 30,
        'min'     => 20,
        'max'     => 40,
        'step'    => 5,
        'unit'    => '%',
        'desc'    => '矛盾升级、冲突酝酿阶段的字数占比。承上启下，逐步拉高读者期待。',
        'section' => '章节结构参数',
    ],
    'ws_segment_ratio_climax' => [
        'label'   => '高潮/爽点释放占比',
        'type'    => 'range',
        'default' => 35,
        'min'     => 20,
        'max'     => 50,
        'step'    => 5,
        'unit'    => '%',
        'desc'    => '爽点爆发、战斗胜利、打脸反转等核心高潮段的字数占比。爽文核心段落，建议不低于25%。',
        'section' => '章节结构参数',
    ],
    'ws_segment_ratio_hook' => [
        'label'   => '钩子收尾占比',
        'type'    => 'range',
        'default' => 15,
        'min'     => 5,
        'max'     => 25,
        'step'    => 5,
        'unit'    => '%',
        'desc'    => '章末钩子/悬念的字数占比。决定读者是否点"下一章"。太短钩子无力，太长拖沓。',
        'section' => '章节结构参数',
    ],
    // ========== 伏笔与记忆参数 ==========
    'ws_foreshadowing_lookback' => [
        'label'   => '伏笔唤醒回溯章数',
        'type'    => 'number',
        'default' => 10,
        'min'     => 3,
        'max'     => 30,
        'step'    => 1,
        'unit'    => '章',
        'desc'    => 'AI 在写章时，会回溯多少章内的已埋设伏笔，从中挑选合适的进行唤醒/回收。',
        'section' => '伏笔与记忆参数',
    ],
    'ws_memory_lookback' => [
        'label'   => '上下文记忆回溯章数',
        'type'    => 'number',
        'default' => 5,
        'min'     => 1,
        'max'     => 15,
        'step'    => 1,
        'unit'    => '章',
        'desc'    => '构建写章 Prompt 时，注入多少章的近期摘要作为上下文。值越大上下文越完整，但 Token 消耗越高。',
        'section' => '伏笔与记忆参数',
    ],
    'ws_embedding_top_k' => [
        'label'   => '语义检索 Top-K',
        'type'    => 'number',
        'default' => 5,
        'min'     => 1,
        'max'     => 20,
        'step'    => 1,
        'unit'    => '条',
        'desc'    => '通过 Embedding 语义检索时，取最相关的多少条记忆原子注入 Prompt。与记忆回溯章数互补。',
        'section' => '伏笔与记忆参数',
    ],
    // ========== AI 生成参数 ==========
    'ws_temperature_outline' => [
        'label'   => '大纲生成 Temperature',
        'type'    => 'range',
        'default' => 0.3,
        'min'     => 0.0,
        'max'     => 1.0,
        'step'    => 0.05,
        'unit'    => '',
        'desc'    => '生成章节大纲时的 AI 温度。低温度（0.2-0.4）输出更稳定、结构更规整；高温度创意更发散。',
        'section' => 'AI 生成参数',
    ],
    'ws_temperature_chapter' => [
        'label'   => '正文生成 Temperature',
        'type'    => 'range',
        'default' => 0.8,
        'min'     => 0.5,
        'max'     => 1.2,
        'step'    => 0.05,
        'unit'    => '',
        'desc'    => '生成章节正文时的 AI 温度。爽文推荐 0.7-0.9：既有创意变化，又不至于放飞自我。',
        'section' => 'AI 生成参数',
    ],
    'ws_max_tokens_outline' => [
        'label'   => '大纲生成 Max Tokens',
        'type'    => 'number',
        'default' => 4096,
        'min'     => 1024,
        'max'     => 8192,
        'step'    => 512,
        'unit'    => 'tokens',
        'desc'    => '生成大纲时允许的最大 Token 数。大纲通常 2000-4000 tokens 足够。',
        'section' => 'AI 生成参数',
    ],
    'ws_max_tokens_chapter' => [
        'label'   => '正文生成 Max Tokens',
        'type'    => 'number',
        'default' => 8192,
        'min'     => 2048,
        'max'     => 16384,
        'step'    => 1024,
        'unit'    => 'tokens',
        'desc'    => '生成正文时允许的最大 Token 数。2000字中文约需 3000-4000 tokens，留足余量防止截断。',
        'section' => 'AI 生成参数',
    ],
    // ========== 质量检查参数 ==========
    'ws_quality_check_enabled' => [
        'label'   => '启用质量检查',
        'type'    => 'select',
        'default' => '1',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '每章写完后，是否自动调用 AI 进行质量评分和诊断。开启后可在写作日志中看到评分详情。',
        'section' => '质量检查参数',
    ],
    'ws_quality_min_score' => [
        'label'   => '质量最低分阈值',
        'type'    => 'range',
        'default' => 6.0,
        'min'     => 1.0,
        'max'     => 10.0,
        'step'    => 0.5,
        'unit'    => '分',
        'desc'    => '质量检查评分低于此值时，系统会标记该章为"需优化"，可在写作日志中查看。',
        'section' => '质量检查参数',
    ],
    // ========== 约束框架 ==========
    'cf_enabled' => [
        'label'   => '启用约束框架',
        'type'    => 'select',
        'default' => '1',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '开启后，每章写完会自动校验结构、语言、情节、节奏等约束条件。违规项会通过 AgentDirectives 指令影响下一章写作，P0 问题还会生成紧急修复指令。',
        'section' => '约束框架',
    ],
    'cf_strict_mode' => [
        'label'   => '严格模式（P0 拦截）',
        'type'    => 'select',
        'default' => '0',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '开启后，检测到 P0 严重违规时会阻止本章落盘并自动重写。关闭时仅写入指令但不拦截。建议先开启约束框架观察一段时间后再考虑严格模式。',
        'section' => '约束框架',
    ],
    'cf_banned_words' => [
        'label'   => '禁用词列表',
        'type'    => 'text',
        'default' => '绝境,反杀,真相,背水,逆袭',
        'desc'    => '章节正文中不允许出现的词语，以英文逗号分隔。系统会统计禁用词使用次数，超过阈值会标记违规。',
        'section' => '约束框架',
    ],
    'cf_max_banned_word_usage' => [
        'label'   => '禁用词最大出现次数',
        'type'    => 'number',
        'default' => 15,
        'min'     => 1,
        'max'     => 50,
        'step'    => 1,
        'desc'    => '单章中禁用词的累计出现次数超过此值将标记为违规。',
        'section' => '约束框架',
    ],
    // ========== 写作质量增强（Agent 系统） ==========
    // 注：ws_rewrite_enabled / ws_rewrite_threshold / ws_rewrite_min_gain
    //     已由「迭代重写」标签页统一管理（api/iterative_config.php），
    //     避免同一参数在两处维护导致数据不一致。
    'ws_critic_enabled' => [
        'label'   => '启用读者视角评分',
        'type'    => 'select',
        'default' => '1',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '每章写完后，从读者视角进行五维评分（爽感/代入感/节奏/新鲜感/追读意愿）。评分结果会影响下一章的写作策略，并生成 AgentDirectives 指令。',
        'section' => '写作质量增强',
    ],
    'ws_style_guard_enabled' => [
        'label'   => '启用风格守护',
        'type'    => 'select',
        'default' => '1',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '检测章节风格是否偏离基线，防止风格漂移。开启后可在写作日志中看到风格漂移告警。',
        'section' => '写作质量增强',
    ],
    'ws_ai_patterns_check_enabled' => [
        'label'   => '启用 AI 痕迹检测',
        'type'    => 'select',
        'default' => '1',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '检测章节中是否含有典型 AI 写作模式（如过度使用排比、空洞抒情等）。检测到问题时会生成指令影响下一章写作风格。',
        'section' => '写作质量增强',
    ],
];
