<?php
/**
 * 写作参数定义配置
 * 
 * 集中管理所有写作参数的元数据定义，包括标签、类型、默认值、范围等。
 * 被 writing_settings.php 和 API 接口共享使用。
 */

return [
    // ========== 基础生成参数 ==========
    'ws_chapter_word_tolerance' => [
        'label'   => '章节字数容差',
        'type'    => 'number',
        'default' => 150,
        'min'     => 50,
        'max'     => 500,
        'step'    => 50,
        'unit'    => '字',
        'desc'    => '允许正文偏离目标字数的范围（±N字）。值越小，字数控制越严格；值越大，AI写作更自然但篇幅更难预测。默认150字约为目标字数的3%-8%。',
        'section' => '基础生成参数',
    ],
    'ws_dynamic_tolerance_ratio' => [
        'label'   => '动态容差比例',
        'type'    => 'number',
        'default' => 10,
        'min'     => 5,
        'max'     => 20,
        'step'    => 1,
        'unit'    => '%',
        'desc'    => '根据目标字数动态计算容差比例。例如：2000字×10%=200字容差。替代固定容差值，使控制比例一致。',
        'section' => '基础生成参数',
    ],
    'ws_min_tolerance' => [
        'label'   => '最小容差字数',
        'type'    => 'number',
        'default' => 100,
        'min'     => 50,
        'max'     => 300,
        'step'    => 50,
        'unit'    => '字',
        'desc'    => '动态容差的下限值。防止目标字数过小时容差太小导致过于严格。',
        'section' => '基础生成参数',
    ],
    'ws_max_tolerance' => [
        'label'   => '最大容差字数',
        'type'    => 'number',
        'default' => 500,
        'min'     => 200,
        'max'     => 1000,
        'step'    => 100,
        'unit'    => '字',
        'desc'    => '动态容差的上限值。防止目标字数过大时容差太大导致控制失效。',
        'section' => '基础生成参数',
    ],
    'ws_outline_batch' => [
        'label'   => '大纲批量生成数',
        'type'    => 'number',
        'default' => 5,
        'min'     => 3,
        'max'     => 50,
        'step'    => 1,
        'unit'    => '章',
        'desc'    => '每次生成大纲时，一次性规划的章节数量。值越大，AI 对长程节奏把控越好，但生成耗时越长。默认5章，可根据网络稳定性调整。',
        'section' => '基础生成参数',
    ],
    'ws_outline_batch_1m' => [
        'label'   => '大纲批量生成数（1M模式）',
        'type'    => 'number',
        'default' => 30,
        'min'     => 10,
        'max'     => 100,
        'step'    => 5,
        'unit'    => '章',
        'desc'    => '1M上下文模型专用。每次可生成更多章节大纲，提升全书连贯性。仅当该模型在“模型设置”中勾选“支持 1M 上下文”时生效。',
        'section' => '基础生成参数',
    ],
    'ws_context_mode' => [
        'label'   => '上下文模式',
        'type'    => 'select',
        'default' => 'auto',
        'options' => [
            'auto'      => '自动（根据模型选择）',
            'compressed'=> '压缩模式（节省token）',
            'full'      => '完整模式（需1M上下文模型）',
        ],
        'desc'    => '压缩模式：仅注入摘要和关键信息，节省 Token。完整模式：在安全预算内尽可能注入历史正文、摘要和关键状态（需勾选模型的“支持 1M 上下文”能力）。自动模式会按模型能力选择。',
        'section' => '基础生成参数',
    ],
    'ws_auto_write_interval' => [
        'label'   => '自动写作间隔',
        'type'    => 'number',
        'default' => 2,
        'min'     => 1,
        'max'     => 60,
        'step'    => 1,
        'unit'    => '秒',
        'desc'    => '连续自动写作时，每章之间的等待间隔。太短可能触发 API 限流；太长拖慢整体进度。',
        'section' => '基础生成参数',
    ],
    // ========== 爽点调度参数 ==========
    'ws_cool_point_density_target' => [
        'label'   => '爽点密度目标值',
        'type'    => 'range',
        'default' => 0.88,
        'min'     => 0.5,
        'max'     => 1.5,
        'step'    => 0.05,
        'unit'    => '个/章',
        'desc'    => '每章平均爽点数量目标。参考值：0.88（《万古神帝》实测密度）。低于0.6读者流失风险高；高于1.2容易审美疲劳。',
        'section' => '爽点调度参数',
    ],
    'ws_cool_point_hunger_threshold' => [
        'label'   => '爽点饥饿阈值',
        'type'    => 'range',
        'default' => 0.6,
        'min'     => 0.3,
        'max'     => 1.0,
        'step'    => 0.05,
        'unit'    => '',
        'desc'    => '某种爽点类型冷却期过多少比例后，可重新参选。值越低，同类型爽点出现越频繁；值越高，类型轮换越均匀。',
        'section' => '爽点调度参数',
    ],
    'ws_double_coolpoint_gap' => [
        'label'   => '双爽点最小间隔',
        'type'    => 'number',
        'default' => 3,
        'min'     => 1,
        'max'     => 10,
        'step'    => 1,
        'unit'    => '章',
        'desc'    => '连续出现"双爽点章"的最小间隔。防止高潮密度过高导致读者疲劳。推荐 2-4 章。',
        'section' => '爽点调度参数',
    ],
    // ========== 章节结构参数 ==========
    'ws_segment_ratio_setup' => [
        'label'   => '铺垫段占比',
        'type'    => 'range',
        'default' => 20,
        'min'     => 10,
        'max'     => 35,
        'step'    => 5,
        'unit'    => '%',
        'desc'    => '每章开头铺垫/引入部分的字数占比。用于交代场景、推进日常、制造悬念。',
        'section' => '章节结构参数',
    ],
    'ws_segment_ratio_rising' => [
        'label'   => '发展段占比',
        'type'    => 'range',
        'default' => 30,
        'min'     => 20,
        'max'     => 40,
        'step'    => 5,
        'unit'    => '%',
        'desc'    => '矛盾升级、冲突酝酿阶段的字数占比。承上启下，逐步拉高读者期待。',
        'section' => '章节结构参数',
    ],
    'ws_segment_ratio_climax' => [
        'label'   => '高潮/爽点释放占比',
        'type'    => 'range',
        'default' => 35,
        'min'     => 20,
        'max'     => 50,
        'step'    => 5,
        'unit'    => '%',
        'desc'    => '爽点爆发、战斗胜利、打脸反转等核心高潮段的字数占比。爽文核心段落，建议不低于25%。',
        'section' => '章节结构参数',
    ],
    'ws_segment_ratio_hook' => [
        'label'   => '钩子收尾占比',
        'type'    => 'range',
        'default' => 15,
        'min'     => 5,
        'max'     => 25,
        'step'    => 5,
        'unit'    => '%',
        'desc'    => '章末钩子/悬念的字数占比。决定读者是否点"下一章"。太短钩子无力，太长拖沓。',
        'section' => '章节结构参数',
    ],
    // ========== 伏笔与记忆参数 ==========
    'ws_foreshadowing_lookback' => [
        'label'   => '伏笔唤醒回溯章数',
        'type'    => 'number',
        'default' => 10,
        'min'     => 3,
        'max'     => 100,
        'step'    => 1,
        'unit'    => '章',
        'desc'    => 'AI 在写章时，会回溯多少章内的已埋设伏笔，从中挑选合适的进行唤醒/回收。',
        'section' => '伏笔与记忆参数',
    ],
    'ws_foreshadow_urgency_enabled' => [
        'label'   => '伏笔截止期优先排序',
        'type'    => 'select',
        'default' => '1',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '按截止期紧急度排序待回收伏笔，并在记忆预算紧张时有限保留最高危伏笔。',
        'section' => '伏笔与记忆参数',
    ],
    'ws_foreshadow_critical_keep' => [
        'label'   => '高危伏笔保留数量',
        'type'    => 'number',
        'default' => 3,
        'min'     => 1,
        'max'     => 3,
        'step'    => 1,
        'unit'    => '条',
        'desc'    => 'Token 预算紧张时，最多保证保留多少条最高危伏笔。上限固定为3条，避免挤占正文上下文。',
        'section' => '伏笔与记忆参数',
    ],
    'ws_returning_character_enabled' => [
        'label'   => '久未登场角色提醒',
        'type'    => 'select',
        'default' => '1',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '重要角色久未出场后重新进入本章大纲时，提醒正文自然唤醒其身份和前情。',
        'section' => '伏笔与记忆参数',
    ],
    'ws_returning_character_gap' => [
        'label'   => '久未登场判定间隔',
        'type'    => 'number',
        'default' => 15,
        'min'     => 5,
        'max'     => 100,
        'step'    => 1,
        'unit'    => '章',
        'desc'    => '重要角色距离上次出场达到多少章后，再次进入大纲时触发前情唤醒提醒。',
        'section' => '伏笔与记忆参数',
    ],
    'ws_returning_character_limit' => [
        'label'   => '单章角色唤醒上限',
        'type'    => 'number',
        'default' => 3,
        'min'     => 1,
        'max'     => 3,
        'step'    => 1,
        'unit'    => '人',
        'desc'    => '单章最多提醒多少名久未登场的重要角色，避免 Prompt 膨胀。',
        'section' => '伏笔与记忆参数',
    ],
    'ws_memory_lookback' => [
        'label'   => '细纲生成回溯章数',
        'type'    => 'number',
        'default' => 16,
        'min'     => 3,
        'max'     => 40,
        'step'    => 1,
        'unit'    => '章',
        'desc'    => '生成章节细纲时，注入多少章的近期大纲作为上下文（用于跨章去重防套路）。值越大去重越准，但 Token 消耗越高。',
        'section' => '伏笔与记忆参数',
    ],
    'ws_embedding_top_k' => [
        'label'   => '语义检索 Top-K',
        'type'    => 'number',
        'default' => 5,
        'min'     => 1,
        'max'     => 20,
        'step'    => 1,
        'unit'    => '条',
        'desc'    => '通过 Embedding 语义检索时，取最相关的多少条记忆原子注入 Prompt。与记忆回溯章数互补。',
        'section' => '伏笔与记忆参数',
    ],
    // ========== AI 生成参数 ==========
    'ws_temperature_outline' => [
        'label'   => '大纲生成 Temperature',
        'type'    => 'range',
        'default' => 0.3,
        'min'     => 0.0,
        'max'     => 1.0,
        'step'    => 0.05,
        'unit'    => '',
        'desc'    => '生成章节大纲时的 AI 温度。低温度（0.2-0.4）输出更稳定、结构更规整；高温度创意更发散。',
        'section' => 'AI 生成参数',
    ],
    'ws_temperature_chapter' => [
        'label'   => '正文生成 Temperature',
        'type'    => 'range',
        'default' => 0.8,
        'min'     => 0.5,
        'max'     => 1.2,
        'step'    => 0.05,
        'unit'    => '',
        'desc'    => '生成章节正文时的 AI 温度。爽文推荐 0.7-0.9：既有创意变化，又不至于放飞自我。',
        'section' => 'AI 生成参数',
    ],
    'ws_max_tokens_outline' => [
        'label'   => '大纲生成 Max Tokens',
        'type'    => 'number',
        'default' => 4096,
        'min'     => 1024,
        'max'     => 8192,
        'step'    => 512,
        'unit'    => 'tokens',
        'desc'    => '生成大纲时允许的最大 Token 数。大纲通常 2000-4000 tokens 足够。',
        'section' => 'AI 生成参数',
    ],
    'ws_max_tokens_chapter' => [
        'label'   => '正文生成 Max Tokens',
        'type'    => 'number',
        'default' => 8192,
        'min'     => 2048,
        'max'     => 16384,
        'step'    => 1024,
        'unit'    => 'tokens',
        'desc'    => '生成正文时允许的最大 Token 数。2000字中文约需 3000-4000 tokens，留足余量防止截断。',
        'section' => 'AI 生成参数',
    ],
    // ========== 质量检查参数 ==========
    'ws_quality_check_enabled' => [
        'label'   => '启用质量检查',
        'type'    => 'select',
        'default' => '1',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '每章写完后，是否自动调用 AI 进行质量评分和诊断。开启后可在写作日志中看到评分详情。',
        'section' => '质量检查参数',
    ],
    'ws_quality_min_score' => [
        'label'   => '质量最低分阈值',
        'type'    => 'range',
        'default' => 6.0,
        'min'     => 1.0,
        'max'     => 10.0,
        'step'    => 0.5,
        'unit'    => '分',
        'desc'    => '质量检查评分低于此值时，系统会标记该章为"需优化"，可在写作日志中查看。',
        'section' => '质量检查参数',
    ],
    // ========== 约束框架 ==========
    'cf_enabled' => [
        'label'   => '启用约束框架',
        'type'    => 'select',
        'default' => '1',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '开启后：①写完校验约束；②把巧合额度/高潮间隔/冲突类型/禁用词累计等状态注入下一章写作提示词；③违规经 Agent 指令影响下章。关闭则不做校验与回灌。',
        'section' => '约束框架',
    ],
    'cf_strict_mode' => [
        'label'   => '严格模式（P0 拦截）',
        'type'    => 'select',
        'default' => '0',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '开启后，检测到 P0 严重违规时会阻止本章落盘并自动重写。关闭时仅写入指令但不拦截。建议先开启约束框架观察一段时间后再考虑严格模式。',
        'section' => '约束框架',
    ],
    'cf_banned_words' => [
        'label'   => '禁用词列表',
        'type'    => 'text',
        'default' => '绝境,反杀,真相,背水,逆袭',
        'desc'    => '章节正文中不允许出现的词语，以英文逗号分隔。系统会统计禁用词使用次数，超过阈值会标记违规。',
        'section' => '约束框架',
    ],
    'cf_max_banned_word_usage' => [
        'label'   => '禁用词最大出现次数',
        'type'    => 'number',
        'default' => 15,
        'min'     => 1,
        'max'     => 50,
        'step'    => 1,
        'desc'    => '单章中禁用词的累计出现次数超过此值将标记为违规。',
        'section' => '约束框架',
    ],
    // ========== 写作质量增强（Agent 系统） ==========
    // 注：ws_rewrite_enabled / ws_rewrite_threshold / ws_rewrite_min_gain
    //     已由「迭代重写」标签页统一管理（api/iterative_config.php），
    //     避免同一参数在两处维护导致数据不一致。
    'ws_critic_enabled' => [
        'label'   => '启用读者视角评分',
        'type'    => 'select',
        'default' => '1',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '每章写完后，从读者视角进行五维评分（爽感/代入感/节奏/新鲜感/追读意愿）。评分结果会影响下一章的写作策略，并生成 AgentDirectives 指令。',
        'section' => '写作质量增强',
    ],
    'ws_critic_interval' => [
        'label'   => '读者评分间隔',
        'type'    => 'number',
        'default' => 1,
        'min'     => 1,
        'max'     => 10,
        'step'    => 1,
        'unit'    => '章',
        'desc'    => '每隔多少章做一次读者视角评分。1=每章（默认）。评分实际是 1-2 次 AI 调用（评分+相对校准），长篇设为 2-5 可显著降低成本；跳过的章节不评分，质量五门检测不受影响。',
        'section' => '写作质量增强',
    ],
    'ws_style_guard_enabled' => [
        'label'   => '启用风格守护',
        'type'    => 'select',
        'default' => '1',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '检测章节风格是否偏离基线，防止风格漂移。开启后可在写作日志中看到风格漂移告警。',
        'section' => '写作质量增强',
    ],
    'ws_ai_patterns_check_enabled' => [
        'label'   => '启用 AI 痕迹检测',
        'type'    => 'select',
        'default' => '1',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '检测章节中是否含有典型 AI 写作模式（如过度使用排比、空洞抒情等）。检测到问题时会生成指令影响下一章写作风格。',
        'section' => '写作质量增强',
    ],

    // ========== 高级 / 实验功能（1000章长程优化）==========
    'ws_story_bible_enabled' => [
        'label'   => '全书圣经',
        'type'    => 'select',
        'default' => '1',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '每隔若干章用 AI 把"世界规则 / 人物现状 / 主线时间线"增量压缩成一份稳定档案，注入写作 Prompt。长篇（数百章以上）强烈建议开启，可大幅减少中段设定/人物漂移。',
        'section' => '高级 / 实验功能',
    ],
    'ws_bible_interval' => [
        'label'   => '全书圣经更新间隔',
        'type'    => 'number',
        'default' => 20,
        'min'     => 5,
        'max'     => 100,
        'step'    => 5,
        'unit'    => '章',
        'desc'    => '每写多少章更新一次全书圣经。越小越新但 AI 调用更频繁。仅在"全书圣经"开启时生效。',
        'section' => '高级 / 实验功能',
    ],
    'ws_fullbook_audit_enabled' => [
        'label'   => '全书一致性体检',
        'type'    => 'select',
        'default' => '1',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '每隔若干章让 AI 对全书做一次宏观体检（伏笔黑洞 / 跨章矛盾 / 节奏停滞 / 支线烂尾），生成报告供在小说页"全书体检"查看。默认只出报告、不自动改稿。',
        'section' => '高级 / 实验功能',
    ],
    'ws_fullbook_audit_interval' => [
        'label'   => '全书体检间隔',
        'type'    => 'number',
        'default' => 50,
        'min'     => 10,
        'max'     => 200,
        'step'    => 10,
        'unit'    => '章',
        'desc'    => '每写多少章做一次全书一致性体检。仅在"全书一致性体检"开启时生效。',
        'section' => '高级 / 实验功能',
    ],
    'ws_pp_wait_sec' => [
        'label'   => '后处理等待上限',
        'type'    => 'number',
        'default' => 120,
        'min'     => 30,
        'max'     => 600,
        'step'    => 30,
        'unit'    => '秒',
        'desc'    => '连续写作时，下一章开写前等待上一章后处理（摘要/记忆/指令落库）完成的最长时间。超时会放行继续写，但下一章可能读到滞后的记忆。后处理已重排，等待窗口内通常只有一次 AI 摘要调用，默认 120 秒即可。',
        'section' => '高级 / 实验功能',
    ],
    'ws_breather_enabled' => [
        'label'   => '呼吸章（节奏调节）',
        'type'    => 'select',
        'default' => '1',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '生成细纲时，约 1/4 章节标记为"蓄力/日常/情感/伏笔章"，不强行安排爽点。打破"每章铺垫→爽点→钩子"的同构感，缓解套路化。收尾期自动不安排。',
        'section' => '高级 / 实验功能',
    ],
    'ws_hook_payoff_enabled' => [
        'label'   => '章末钩子回收',
        'type'    => 'select',
        'default' => '1',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '写每章时强制要求开头回收上一章结尾的悬念钩子；写完后验证是否真的回收，发现"悬挂钩子"会提醒下一章补上，避免悬念烂尾。',
        'section' => '高级 / 实验功能',
    ],
    'ws_hook_payoff_ai' => [
        'label'   => '钩子回收用 AI 判定',
        'type'    => 'select',
        'default' => '0',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '开启后用一次轻量 AI 判断"本章是否回收了上章钩子"（更准但每章多一次调用）；关闭则用关键词重叠启发式（零额外成本，保守只标明显遗漏）。',
        'section' => '高级 / 实验功能',
    ],
    'ws_style_exemplar_enabled' => [
        'label'   => '文风范本（照着写）',
        'type'    => 'select',
        'default' => '1',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '写每章时注入本书评分最高章节的一段作为文风范本，让 AI"照着写"而非"按规则写"（只学写法、不抄情节）。写够几章、有评分后生效，可明显稳定文笔。',
        'section' => '高级 / 实验功能',
    ],
    'ws_voice_profile_enabled' => [
        'label'   => '角色语音指纹',
        'type'    => 'select',
        'default' => '1',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '每隔若干章为缺指纹的主要角色自动设计互相区分的说话风格（句长/口癖/禁用词/语气），注入写作 Prompt，让不同角色对话有辨识度，避免"所有人一个腔调"。',
        'section' => '高级 / 实验功能',
    ],
    'ws_turning_point_check' => [
        'label'   => '转折点兑现验证',
        'type'    => 'select',
        'default' => '1',
        'options' => ['1' => '开启', '0' => '关闭'],
        'desc'    => '生成细纲后，核对"全书故事大纲里本批应触发的关键转折点"是否真的写进了章节细纲；缺失则自动定向返修补入。防止顶层规划的主线被底层细纲悄悄跳过（长篇防跑偏）。',
        'section' => '高级 / 实验功能',
    ],
    'ws_temperature_outline_gen' => [
        'label'   => '细纲生成温度',
        'type'    => 'range',
        'default' => 0.75,
        'min'     => 0.2,
        'max'     => 1.3,
        'step'    => 0.05,
        'desc'    => '生成章节细纲时的采样温度。越高越发散、越不套路，但偶尔会偏离设定；越低越稳但容易套路化。摘要/抽取等结构化任务不受此项影响。建议 0.6–0.9。',
        'section' => '高级 / 实验功能',
    ],
];
